language: php
sudo: false

php:
  - 5.6

matrix:
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --no-interaction
  - cd ../../../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv vih-build profiles/vih_dk
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --prepare-install profiles/vih_dk/build-vih.make --yes
  - cd ../

  # Setup files
  - chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:

  - cd drupal
  - drush si vih_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush en vih_demo --yes
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done
  - cd profiles/vih_dk/tests/behat

  # Make the Travis tests repos agnostic by injecting drupal_root with BEHAT_PARAMS
  - BUILD_OWNER=`dirname $TRAVIS_BUILD_DIR`
  - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$BUILD_OWNER/drupal"

script:

  # Test if any features are overridden.
  - ../../scripts/check-overridden.sh

  # Run Behat tests
  - ./bin/behat --config behat.travis.yml
